export const AUTH_MODULE_OPTIONS = 'AUTH_MODULE_OPTIONS'

export const ROLES_DECORATOR_METADATA_KEY = 'roles'
export const PERMISSIONS_DECORATOR_METADATA_KEY = 'permissions'
export const M2M_CLIENT_ACCESS_DECORATOR_METADATA_KEY = 'm2mClientAccess'
